### ISSUE TITLE
jdk 9 compilation fails

### ISSUE THREAD

**Issue by sreev** [bigdatagenomics/bdg-formats#165]
```
[INFO] Compiling 25 source files to /Users/svaddi/SreeVaddi/source/github/sreev/bdg-formats/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Source option 1.5 is no longer supported. Use 1.6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.232 s
[INFO] Finished at: 2018-05-19T07:42:19-07:00
[INFO] ------------------------------------------------------------------------

```

**Comment by heuermh** [comment]
Hello @sreev, thank you for submitting this issue!

Are you planning to use `bdg-formats` outside of Apache Spark?  As far as I know, support for JDK 9/10 in Apache Spark is still some time off, and we won't bump downstream in ADAM until Spark does.

**Comment by fnothaft** [comment]
@heuermh agreed about not bumping to Java 9/10 until Spark does, but from looking at https://github.com/bigdatagenomics/bdg-formats/pull/166, it doesn't look like any of the changes would preclude us from still building against Java 8 (other than the explicit bump to Java 9, of course, but we could take all of the change except for that). If that's the case, then I'd suggest we merge so that the _eventual_ move to Java 9/10 is easier.
